FROM container-registry.oracle.com/database/free:latest

ENV ORACLE_PDB=FREEPDB1 \
    ORACLE_PWD=Admin123 \
    ORACLE_CHARACTERSET=AL32UTF8

COPY scripts/script-bd.sql /opt/oracle/scripts/setup/01-script-bd.sql

USER root
RUN chmod 644 /opt/oracle/scripts/setup/01-script-bd.sql
USER oracle