FROM gvenzl/oracle-xe:21-slim

# Senha do usuário SYSTEM
ENV ORACLE_PASSWORD=Admin123

COPY scripts/script-bd.sql /container-entrypoint-initdb.d/01-script-bd.sql

USER root
RUN chmod 644 /container-entrypoint-initdb.d/01-script-bd.sql
USER oracle
